name: Maven Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Maven Release
      uses: qcastel/github-actions-maven-release@v1.12.41
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
