name: Maven Release

on:
  workflow_dispatch:
    inputs:
        releaseVersion:
          description: "Define the release version"
          required: true
          default: ""
        developmentVersion:
          description: "Define the snapshot version"
          required: true
          default: ""

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64

    - name: Maven Release
      uses: qcastel/github-actions-maven-release@v1.12.41
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
        gpg-enabled: true
        gpg-key-id: ${{ secrets.GPG_KEY_ID }}
        gpg-key: ${{ secrets.GPG_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        maven-development-version-number: ${{ github.event.inputs.developmentVersion }}
        maven-release-version-number: ${{ github.event.inputs.releaseVersion }}
        release-branch-name: main
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
